# Generated by Django 6.1.1 on 2026-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_question_question_type_mistake_testsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('video', 'Video'), ('link', 'Useful Link')], default='video', max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Preparing Video',
                'verbose_name_plural': 'Preparing Videos',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
